version: 2

workflows:
  version: 2
  dist-compile:
    jobs:
      - compile:
          filters:
            branches:
              only:  # only branches matching the below regex filters will run
                - exmg-lls
                - feature/circleci

jobs:
  compile:
    docker:
      - image: ubuntu:18.04
    steps:
      - run:
          name: dependencies
          command: |
            apt-get update
            apt-get install -y \
              alsa \
              apt-utils \
              automake \
              autoconf \
              build-essential \
              cmake \
              dkms \
              git-core \
              libasound2-dev \
              libass-dev \
              libfreetype6-dev \
              libgl1-mesa-glx \
              libgl1 \
              libpulse-dev \
              libssl-dev \
              libtool \
              libva-dev \
              libva2 \
              libva-drm2 \
              libva-x11-2 \
              libxv1 \
              libx264-152 \
              libx264-dev \
              nasm \
              pkg-config \
              pulseaudio \
              texinfo \
              yasm \
              zlib1g-dev
      - run:
          name: vmaf
          command: |
            cd /tmp
            git clone https://github.com/Netflix/vmaf.git
            cd vmaf
            git checkout tags/v1.3.15
            cd ptools
            make
            cd ../wrapper
            make -j8
            cd ..
            sudo make install
      - run:
          name: SVT
          command: |
            cd /tmp
            git clone https://github.com/OpenVisualCloud/SVT-HEVC.git
            cd SVT-HEVC/Build/linux
            ./build.sh release static install
      - run:
          name: SRT
          command: |
            apt install -y tclsh
            cd /tmp
            git clone https://github.com/Haivision/srt.git
            cd srt
            ./configure
            make
            make install
      - checkout
      - run:
          name: configure
          command: |
            ./configure  \
              --enable-gpl \
              --enable-nonfree \
              --enable-openssl \
              --enable-version3 \
              --enable-static \
              --disable-sdl2 \
              --disable-debug \
              --disable-ffplay \
              --disable-libxcb \
              --disable-libxcb-shm \
              --disable-indev=sndio \
              --disable-outdev=sndio \
              --disable-outdev=xv \
              --enable-libx264 \
              --enable-libpulse \
              --enable-vaapi \
              --enable-libfreetype \
              --enable-fontconfig \
              --enable-libvmaf \
              --enable-libsvthevc \
              --enable-libsrt \
              --extra-libs="-lpthread -lm" \
              --pkg-config-flags=--static
      - run:
          name: make
          command: |
            make -j2
            mkdir /tmp/artifacts
            cp ffmpeg_g /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts