version: 2

workflows:
  version: 2
  dist-compile:
    jobs:
      - shellcheck
      - compile:
          filters:
            branches:
              only:  # only branches matching the below regex filters will run
                - exmg-lls
                - feature/circleci


jobs:
  compile:
    parallelism: 2
    docker:
      - image: gcc:8.2
    steps:
      - run: apt-get update
      - run: apt-get install -y build-essential
      - checkout

  shellcheck:
    docker:
      - image: koalaman/shellcheck-alpine:stable
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: |
            find . -type f -name '*.sh' | wc -l
            find . -type f -name '*.sh' | xargs shellcheck --external-sources