version: 2

workflows:
  version: 2
  dist-compile:
    jobs:
      - compile:
          filters:
            branches:
              only:  # only branches matching the below regex filters will run
                - exmg-lls
                - feature/circleci

jobs:
  compile:
    docker:
      - image: joepexmg/livery-docker-primary:0.0.3
        auth:
          username: joepexmg
          password: $DOCKERHUB_PASSWORD_JOEPEXMG
    steps:
      - checkout
      - run:
          name: configure
          command: |
            ./configure  \
              --enable-gpl \
              --enable-nonfree \
              --enable-openssl \
              --enable-version3 \
              --enable-static \
              --disable-sdl2 \
              --disable-debug \
              --disable-ffplay \
              --disable-libxcb \
              --disable-libxcb-shm \
              --disable-indev=sndio \
              --disable-outdev=sndio \
              --disable-outdev=xv \
              --enable-libx264 \
              --enable-libpulse \
              --enable-vaapi \
              --enable-libfreetype \
              --enable-fontconfig \
              --extra-libs="-lpthread -lm" \
              --pkg-config-flags=--static \
              --prefix="output"
      - run:
          name: make
          command: |
            make -j2
      - run:
          name: make install
          command: |
            make install
      - run:
          name: create libs zip
          command: |
            cd output
            zip -r -1 ffmpeglib.zip lib/ include/
      - run:
          name: move artifacts
          command: |
            mkdir /tmp/artifacts
            cp ffmpeg_g /tmp/artifacts
            cp output/ffmpeglib.zip /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts